name: Deploy to Development
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Tyk Sync
        run: |
          wget https://github.com/TykTechnologies/tyk-sync/releases/latest/download/tyk-sync-linux-amd64.tar.gz
          tar -xzf tyk-sync-linux-amd64.tar.gz
          chmod +x tyk-sync
      
      - name: Validate API Definitions
        run: |
          for file in apis/*/api-definition.json; do
            echo "Validating $file"
            jq empty "$file" || exit 1
          done
      
      - name: Deploy to Development
        env:
          TYK_DB_LICENSEKEY: ${{ secrets.TYK_LICENSE }}
          TYK_DB_IMPORTAPIKEY: ${{ secrets.TYK_DEV_SECRET }}
        run: |
          ./tyk-sync sync \
            --dashboard ${{ vars.TYK_DEV_URL }} \
            --secret ${{ secrets.TYK_DEV_SECRET }} \
            --path ./apis \
            --update
      
      - name: Run API Tests
        run: |
          # Run automated API tests
          npm install
          npm run test:api:dev
